# ベースイメージとしてNode.jsを使用
FROM node:20-alpine

# 作業ディレクトリを設定
WORKDIR /usr/src/app

# 正しいディレクトリからpackage.jsonとpackage-lock.jsonをコピー
COPY folder-creation/package*.json ./

# npmで依存関係をインストール
RUN npm install

# Angular CLIをグローバルにインストール
RUN npm install -g @angular/cli

# アプリケーションのソースコードをコピー
COPY folder-creation/ ./

# ポートを公開
EXPOSE 4200

# アプリケーションを起動
CMD ["npm", "run", "dev"]